### ISSUE TITLE
Excessive render pass restarts for each draw

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FNA3D#165]
Pretty sure this is https://github.com/FNA-XNA/FNA3D/commit/b1c55d70d10a16de432e906e35c920564206adb7 acting up - basically all you need to do is run a game with Vulkan and inspect a RenderDoc capture; FEZ in particular showed an alarming number of render passes and our barrier system ending render passes appears to be the culprit. We'll probably need to revert this commit and instead add another check to ensure that there's a _reason_ for the barrier (not just the layout, but memory activity as well).

**Comment by thatcosmonaut** [comment]
Resolved by https://github.com/FNA-XNA/FNA3D/pull/166
