### ISSUE TITLE
Clamp depth clear values

### ISSUE THREAD

**Issue by kg** [FNA-XNA/FNA3D#34]
While MSDN says that ID3D11DeviceContext::ClearDepthStencilView clamps the clear depth to the range of 0-1, it doesn't appear to actually do that. On my machine if you set the clear depth to -1 it just doesn't clear the depth buffer at all (or it sets it to 1, it's hard to tell which in renderdoc).

Naturally the code passing a depth of -1 is the broken code, but in classic OpenGL FNA this does what you'd expect it to (the depth value is clamped) and in D3D11 FNA3D it is busted. I think it's worth just clamping the input to the clear API, either in FNA or FNA3D.

**Comment by flibitijibibo** [comment]
Per the Discord discussion I believe this is as resolved as it can get:

- [glClearDepth](glClearDepth) clamps to [0, 1]
- [D3D11](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-cleardepthstencilview) clamps to [0, 1]
- [Vulkan](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkClearDepthStencilValue.html) requires the application to clamp manually ([now fixed](https://github.com/FNA-XNA/FNA3D/commit/5a29e630ae4353deec7c1126a6b0834dc3ecfba0))

Values outside this range where the runtime fails to clamp are considered undefined behavior in the general case, but accurate behavior in the XNA case, as it calls IDirect3DDevice9_Clear with the parameter unmodified.
