### ISSUE TITLE
Bug with the D3D11 renderer (Full Screen Scaling)

### ISSUE THREAD

**Issue by i-am-tanmay** [FNA-XNA/FNA3D#38]
Here is the project as requested by @flibitijibibo at [https://github.com/FNA-XNA/FNA/issues/328](https://github.com/FNA-XNA/FNA/issues/328) relating to scaling to full screen not working properly.

[Project Files : Google Drive](https://drive.google.com/file/d/1QfELYPCrcRT4behlSjjbA34Ze2edb1em/view?usp=sharing)

**Comment by flibitijibibo** [comment]
Our D3D11 developer is looking at this now, but while they're working on that: Do not just lump code into an existing project file and hack the repo to death. Make a separate solution and separate exe project in a separate folder, then add and reference FNA.csproj separately, under the Projects tab of the Reference Manager: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2019

Hacking the FNA project essentially makes it impossible to tell what's yours and what you've broken in FNA; luckily you left the .git metadata so I was able to `git diff -w` and see what happened, but that's not typically what we want to spend our time doing for basic unit tests.

**Comment by flibitijibibo** [comment]
Standalone test case, which confirms the issue with D3D11:

```
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

class Program : Game
{
	static void Main(string[] args)
	{
		using (Program p = new Program())
		{
			p.Run();
		}
	}

	Program()
	{
		GraphicsDeviceManager g = new GraphicsDeviceManager(this);
		g.PreferredBackBufferWidth = 320;
		g.PreferredBackBufferHeight = 180;
		g.IsFullScreen = true;
		g.ApplyChanges(); // This is bad, do not keep this line!
	}

	SpriteBatch batch;
	Texture2D texture;

	protected override void LoadContent()
	{
		batch = new SpriteBatch(GraphicsDevice);
		texture = new Texture2D(GraphicsDevice, 64, 64);
		Color[] c = new Color[64 * 64];
		for (int i = 0; i < (64 * 64); i += 1)
		{
			c[i] = Color.Red;
		}
		texture.SetData(c);
	}

	protected override void UnloadContent()
	{
		batch.Dispose();
		texture.Dispose();
	}

	protected override void Draw(GameTime gameTime)
	{
		GraphicsDevice.Clear(Color.CornflowerBlue);
		batch.Begin();
		batch.Draw(
			texture,
			new Vector2(320 - 64, 180 - 64),
			Color.White
		);
		batch.End();
	}
}
```

**Comment by TheSpydog** [comment]
This bug should be fixed as of [the latest commit](https://github.com/FNA-XNA/FNA3D/commit/cc351771d872542f584cf83e862b73417cd5a8fc). Let me know if this works for you.

**Comment by flibitijibibo** [comment]
fnalibs.tar.bz2 has been updated with the latest FNA3D revision.

**Comment by i-am-tanmay** [comment]
> Our D3D11 developer is looking at this now, but while they're working on that: Do not just lump code into an existing project file and hack the repo to death. Make a separate solution and separate exe project in a separate folder, then add and reference FNA.csproj separately, under the Projects tab of the Reference Manager: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2019
> 
> Hacking the FNA project essentially makes it impossible to tell what's yours and what you've broken in FNA; luckily you left the .git metadata so I was able to `git diff -w` and see what happened, but that's not typically what we want to spend our time doing for basic unit tests.

What do you mean hack the FNA project? I changed nothing in the FNA files, untouched.

**Comment by flibitijibibo** [comment]
This should explain the difference between a solution and a project: https://www.monodevelop.com/documentation/solutions-and-projects-explained/

Create a new solution and project, add FNA as a separate project, reference FNA from your new MyProject.

But ignoring that for now... does the new FNA3D fix the original issue?

**Comment by i-am-tanmay** [comment]
Ohh got it!

And i think the libs are not updated on the website? It still says last update August 4. But I tried it anyway and it's not working cause maybe it's the old one there.

**Comment by flibitijibibo** [comment]
md5sums to verify you have the latest:

```
4bc5adfbcb108551820175d0e7b0062c  fnalibs.tar.bz2
6390ef161dc9845d701b2a09cdc5642b  x86/FNA3D.dll
8adf0432af65de2bef7b29f8bec37328  x64/FNA3D.dll
```

**Comment by i-am-tanmay** [comment]
`1b7b04a7dadeb907d34fc2d12cc0b8e5c0cce3da fnalibs.tar.bz2`

**Comment by i-am-tanmay** [comment]
Yes working!
