### ISSUE TITLE
GraphicsDevice.DrawUserIndexedPrimitives() throws SEHException.

### ISSUE THREAD

**Issue by jsmars** [FNA-XNA/FNA3D#49]
As discussed on discord I have a few different calls to `GraphicsDevice.DrawUserIndexedPrimitives()` that throw 

> System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

Enabling native debugging gives us this additional information:

> D3D11 CORRUPTION: ID3D11Device::CreateInputLayout: Semantic name cannot be NULL (or pointer is corrupt). Declaration entry [1]. [ MISCELLANEOUS CORRUPTION #13: CORRUPTED_PARAMETER1]
> Exception thrown at 0x751143D2 (KernelBase.dll) in jsmarsSamples.exe: 0x0000087D (parameters: 0x00000000, 0x00EFAF94, 0x00EFA3CC).
> Exception thrown: 'System.Runtime.InteropServices.SEHException' in FNA.dll

This happens while using custom effects, but also for `BasicEffect `and the stock `VertexPositionColorTexture`, hopefully they are at least caused by the same thing.

For the basic effect I've narrowed it down to the following lines:
```
effect.EnableDefaultLighting();
effect.TextureEnabled = true;
```
Skipping the last one changes the exception to:

> System.InvalidOperationException: 'Could not compile input layout! Error Code: 80070057'

I've attached a sample project that throws the exception.
[SemanticCrash.zip](https://github.com/FNA-XNA/FNA3D/files/5190797/SemanticCrash.zip)

**Comment by jsmars** [comment]
Did some more digging and updated the sample a bit. It should now render two rotating cubes when working correctly. One vertex colored and one wireframe.
[SemanticCrash2.zip](https://github.com/FNA-XNA/FNA3D/files/5194052/SemanticCrash2.zip)

There is also a (related?) issue when drawing `LineStrip` where some vertex positions seem corrupt in some way, this is however only for DX11 and seems to work correctly on Vulkan (as well as OpenGL). Not sure if this should be handled here or if a separate issue should be opened for it?

Here it is in OpenGL:
![image](https://user-images.githubusercontent.com/5105918/92580467-b0942c80-f28e-11ea-8280-d56d04734f3f.png)

Also looks fine in Vulkan:
![image](https://user-images.githubusercontent.com/5105918/92580563-d0c3eb80-f28e-11ea-9c32-7aa711eda250.png)

but DX11 makes the LineStrip render incorrectly (EnableDefaultLighting is commented out to avoid the exception):
![image](https://user-images.githubusercontent.com/5105918/92580662-f0f3aa80-f28e-11ea-8769-3343631dbab0.png)

Also, while calling `EnableDefaultLighting` on Vulkan doesn't cause the crash, it does seem to disable Vertex Colors.
![image](https://user-images.githubusercontent.com/5105918/92581808-6b70fa00-f290-11ea-91a4-b4775be3f570.png)

However, in my main conversion project, Vulkan does also seem to crash on the same object but with a different exception, I haven't been able to reproduce it in the sample yet though, will post when I figure it out but it may be something unrelated.
![image](https://user-images.githubusercontent.com/5105918/92582147-e0443400-f290-11ea-9434-14941e61b783.png)

**Comment by flibitijibibo** [comment]
The LineStrip bug is invalid behavior in the test program - you need to have _all_ of the vertex attributes that the shader requests, you are only providing POSITION0 and COLOR0 with no TEXCOORD0. OpenGL may be more tolerant of this, but it is still wasted performance when you do this (as ARB_debug_output will complain about, notably on NVIDIA hardware).

The fix for the LineStrip bug is either to use VertexPositionColorTexture, or set `effect.TextureEnabled = false` for the wireframe render. Either way, `effect.TextureEnabled = true` should be set before rendering the color cube, but note that doing this will fix the vertex behavior, but result in the black cube since no texture has been bound, which is accurate behavior to the best of my knowledge.

Overall it's extremely clear that the bug is _completely_ invalid vertex/sampler behavior, and is not actually FNA3D. Be sure to check your vertex declarations and make sure that they _exactly_ match the vertex shader input semantics, or you're basically demanding that the driver do undefined behaviors that are also slow.

**Comment by flibitijibibo** [comment]
Attached is the program with fixed vertex attributes. Note that the behavior is still pretty off because the Normal values are pretty much undefined:

```
using System;
using System.Runtime.InteropServices;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace SemanticCrash
{
    static class Program
    {
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("FNA3D_FORCE_DRIVER", "OpenGL");
            //Environment.SetEnvironmentVariable("FNA3D_FORCE_DRIVER", "Vulkan");

            using (Game1 game = new Game1())
            {
                game.Run();
            }
        }
    }

    public class Game1 : Microsoft.Xna.Framework.Game
    {
        GraphicsDeviceManager graphics;
        VertexPositionNormalColor[] vertices;
        int[] indices;
        VertexPositionNormalColor[] vertices2;
        short[] indices2;
        BasicEffect effect;
        RasterizerState wireRaster = new RasterizerState() { CullMode = CullMode.None, FillMode = FillMode.WireFrame, };
        float rotation;

        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";

            #region Colored Cube Triangle list

            //TODO: Get vertex building from MeshHelper class?
            vertices = new VertexPositionNormalColor[6 * 4];
            indices = new int[12 * 3];
            int v = 0;
            int n = 0;

            indices[v++] = 3; indices[v++] = 1; indices[v++] = 0;
            indices[v++] = 0; indices[v++] = 2; indices[v++] = 3;
            indices[v++] = 4; indices[v++] = 6; indices[v++] = 5;
            indices[v++] = 6; indices[v++] = 7; indices[v++] = 5;
            indices[v++] = 8; indices[v++] = 10; indices[v++] = 11;
            indices[v++] = 11; indices[v++] = 9; indices[v++] = 8;
            indices[v++] = 12; indices[v++] = 14; indices[v++] = 15;
            indices[v++] = 15; indices[v++] = 13; indices[v++] = 12;
            indices[v++] = 16; indices[v++] = 18; indices[v++] = 19;
            indices[v++] = 19; indices[v++] = 17; indices[v++] = 16;
            indices[v++] = 20; indices[v++] = 22; indices[v++] = 23;
            indices[v++] = 23; indices[v++] = 21; indices[v++] = 20;
            
            var x = 1f / 2;
            var y = 1f / 2;
            var z = 1f / 2;
            vertices[0].Position = vertices[17].Position = vertices[20].Position = new Vector3(-x, y, -z);
            vertices[1].Position = vertices[13].Position = vertices[16].Position = new Vector3(x, y, -z);
            vertices[2].Position = vertices[8].Position = vertices[21].Position = new Vector3(-x, -y, -z);
            vertices[3].Position = vertices[9].Position = vertices[12].Position = new Vector3(x, -y, -z);
            vertices[4].Position = vertices[10].Position = vertices[23].Position = new Vector3(-x, -y, z);
            vertices[5].Position = vertices[11].Position = vertices[14].Position = new Vector3(x, -y, z);
            vertices[6].Position = vertices[19].Position = vertices[22].Position = new Vector3(-x, y, z);
            vertices[7].Position = vertices[15].Position = vertices[18].Position = new Vector3(x, y, z);
            
            var rnd = new Random();
            for (int i = 0; i < vertices.Length; i++)
                vertices[i].Color = new Color((byte)rnd.Next(255), (byte)rnd.Next(255), (byte)rnd.Next(255));

            #endregion

            #region Wire Cube Line Strip

            const float r = 0.5f;
            vertices2 = new VertexPositionNormalColor[]
            {
                    new VertexPositionNormalColor(new Vector3(-r, r, -r), Vector3.Zero, Color.Yellow),
                    new VertexPositionNormalColor(new Vector3(r, r, -r), Vector3.Zero, Color.Yellow),
                    new VertexPositionNormalColor(new Vector3(-r, -r, -r), Vector3.Zero, Color.Yellow),
                    new VertexPositionNormalColor(new Vector3(r, -r, -r), Vector3.Zero, Color.Yellow),
                    new VertexPositionNormalColor(new Vector3(-r, r, r), Vector3.Zero, Color.Yellow),
                    new VertexPositionNormalColor(new Vector3(r, r, r), Vector3.Zero, Color.Yellow),
                    new VertexPositionNormalColor(new Vector3(-r, -r, r), Vector3.Zero, Color.Yellow),
                    new VertexPositionNormalColor(new Vector3(r, -r, r), Vector3.Zero, Color.Yellow),
            };
            indices2 = new short[] { 1, 3, 7, 5, 1, 0, 2, 3, 7, 6, 2, 0, 4, 5, 4, 6 };

            #endregion
        }

        protected override void LoadContent()
        {
            effect = new BasicEffect(GraphicsDevice);
            effect.VertexColorEnabled = true;
            effect.EnableDefaultLighting();
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);
            effect.View = Matrix.CreateLookAt(new Vector3(3, 3, 3), Vector3.Zero, Vector3.UnitZ);
            effect.Projection = Matrix.CreatePerspectiveFieldOfView(0.5f, 1280f / 720f, 0.01f, 1000);

            // Draw colored cube using trianglelist
            effect.World = Matrix.CreateRotationZ(rotation += 0.01f) * Matrix.CreateTranslation(-1, 0, 0) * Matrix.CreateRotationZ(rotation / -2);
            foreach (var pass in effect.CurrentTechnique.Passes)
            {
                pass.Apply();
                GraphicsDevice.DrawUserIndexedPrimitives(PrimitiveType.TriangleList, vertices, 0, vertices.Length, indices, 0, indices.Length / 3);
            }

            // Draw wireframe cube
            effect.World = Matrix.CreateRotationZ(rotation += 0.01f) * Matrix.CreateTranslation(1, 0, 0) * Matrix.CreateRotationZ(rotation / -2);
            foreach (EffectPass pass in effect.CurrentTechnique.Passes)
            {
                pass.Apply();
                GraphicsDevice.DrawUserIndexedPrimitives(PrimitiveType.LineStrip, vertices2, 0, vertices2.Length, indices2, 0, indices2.Length - 1);
            }

            base.Draw(gameTime);
        }
    }

	[Serializable]
	[StructLayout(LayoutKind.Sequential, Pack = 1)]
	public struct VertexPositionNormalColor : IVertexType
	{
		#region Private Properties

		VertexDeclaration IVertexType.VertexDeclaration
		{
			get
			{
				return VertexDeclaration;
			}
		}

		#endregion

		#region Public Variables

		public Vector3 Position;
		public Vector3 Normal;
		public Color Color;

		#endregion

		#region Public Static Variables

		public static readonly VertexDeclaration VertexDeclaration;

		#endregion

		#region Private Static Constructor

		static VertexPositionNormalColor()
		{
			VertexDeclaration = new VertexDeclaration(
				new VertexElement[]
				{
					new VertexElement(
						0,
						VertexElementFormat.Vector3,
						VertexElementUsage.Position,
						0
					),
					new VertexElement(
						12,
						VertexElementFormat.Vector3,
						VertexElementUsage.Normal,
						0
					),
					new VertexElement(
						24,
						VertexElementFormat.Color,
						VertexElementUsage.Color,
						0
					)
				}
			);
		}

		#endregion

		#region Public Constructor

		public VertexPositionNormalColor(
			Vector3 position,
			Vector3 normal,
			Color color
		) {
			Position = position;
			Normal = normal;
			Color = color;
		}

		#endregion
	}
}
```

**Comment by flibitijibibo** [comment]
Alternate version with no custom vertex struct, simply by disabling lighting which removes the need for `NORMAL0`:

```
using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace SemanticCrash
{
    static class Program
    {
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("FNA3D_FORCE_DRIVER", "OpenGL");
            //Environment.SetEnvironmentVariable("FNA3D_FORCE_DRIVER", "Vulkan");

            using (Game1 game = new Game1())
            {
                game.Run();
            }
        }
    }

    public class Game1 : Microsoft.Xna.Framework.Game
    {
        GraphicsDeviceManager graphics;
        VertexPositionColor[] vertices;
        int[] indices;
        VertexPositionColor[] vertices2;
        short[] indices2;
        BasicEffect effect;
        RasterizerState wireRaster = new RasterizerState() { CullMode = CullMode.None, FillMode = FillMode.WireFrame, };
        float rotation;

        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";

            #region Colored Cube Triangle list

            //TODO: Get vertex building from MeshHelper class?
            vertices = new VertexPositionColor[6 * 4];
            indices = new int[12 * 3];
            int v = 0;
            int n = 0;

            indices[v++] = 3; indices[v++] = 1; indices[v++] = 0;
            indices[v++] = 0; indices[v++] = 2; indices[v++] = 3;
            indices[v++] = 4; indices[v++] = 6; indices[v++] = 5;
            indices[v++] = 6; indices[v++] = 7; indices[v++] = 5;
            indices[v++] = 8; indices[v++] = 10; indices[v++] = 11;
            indices[v++] = 11; indices[v++] = 9; indices[v++] = 8;
            indices[v++] = 12; indices[v++] = 14; indices[v++] = 15;
            indices[v++] = 15; indices[v++] = 13; indices[v++] = 12;
            indices[v++] = 16; indices[v++] = 18; indices[v++] = 19;
            indices[v++] = 19; indices[v++] = 17; indices[v++] = 16;
            indices[v++] = 20; indices[v++] = 22; indices[v++] = 23;
            indices[v++] = 23; indices[v++] = 21; indices[v++] = 20;
            
            var x = 1f / 2;
            var y = 1f / 2;
            var z = 1f / 2;
            vertices[0].Position = vertices[17].Position = vertices[20].Position = new Vector3(-x, y, -z);
            vertices[1].Position = vertices[13].Position = vertices[16].Position = new Vector3(x, y, -z);
            vertices[2].Position = vertices[8].Position = vertices[21].Position = new Vector3(-x, -y, -z);
            vertices[3].Position = vertices[9].Position = vertices[12].Position = new Vector3(x, -y, -z);
            vertices[4].Position = vertices[10].Position = vertices[23].Position = new Vector3(-x, -y, z);
            vertices[5].Position = vertices[11].Position = vertices[14].Position = new Vector3(x, -y, z);
            vertices[6].Position = vertices[19].Position = vertices[22].Position = new Vector3(-x, y, z);
            vertices[7].Position = vertices[15].Position = vertices[18].Position = new Vector3(x, y, z);
            
            var rnd = new Random();
            for (int i = 0; i < vertices.Length; i++)
                vertices[i].Color = new Color((byte)rnd.Next(255), (byte)rnd.Next(255), (byte)rnd.Next(255));

            #endregion

            #region Wire Cube Line Strip

            const float r = 0.5f;
            vertices2 = new VertexPositionColor[]
            {
                    new VertexPositionColor(new Vector3(-r, r, -r), Color.Yellow),
                    new VertexPositionColor(new Vector3(r, r, -r), Color.Yellow),
                    new VertexPositionColor(new Vector3(-r, -r, -r), Color.Yellow),
                    new VertexPositionColor(new Vector3(r, -r, -r), Color.Yellow),
                    new VertexPositionColor(new Vector3(-r, r, r), Color.Yellow),
                    new VertexPositionColor(new Vector3(r, r, r), Color.Yellow),
                    new VertexPositionColor(new Vector3(-r, -r, r), Color.Yellow),
                    new VertexPositionColor(new Vector3(r, -r, r), Color.Yellow),
            };
            indices2 = new short[] { 1, 3, 7, 5, 1, 0, 2, 3, 7, 6, 2, 0, 4, 5, 4, 6 };

            #endregion
        }

        protected override void LoadContent()
        {
            effect = new BasicEffect(GraphicsDevice);
            effect.VertexColorEnabled = true;
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);
            effect.View = Matrix.CreateLookAt(new Vector3(3, 3, 3), Vector3.Zero, Vector3.UnitZ);
            effect.Projection = Matrix.CreatePerspectiveFieldOfView(0.5f, 1280f / 720f, 0.01f, 1000);

            // Draw colored cube using trianglelist
            effect.World = Matrix.CreateRotationZ(rotation += 0.01f) * Matrix.CreateTranslation(-1, 0, 0) * Matrix.CreateRotationZ(rotation / -2);
            foreach (var pass in effect.CurrentTechnique.Passes)
            {
                pass.Apply();
                GraphicsDevice.DrawUserIndexedPrimitives(PrimitiveType.TriangleList, vertices, 0, vertices.Length, indices, 0, indices.Length / 3);
            }

            // Draw wireframe cube
            effect.World = Matrix.CreateRotationZ(rotation += 0.01f) * Matrix.CreateTranslation(1, 0, 0) * Matrix.CreateRotationZ(rotation / -2);
            foreach (EffectPass pass in effect.CurrentTechnique.Passes)
            {
                pass.Apply();
                GraphicsDevice.DrawUserIndexedPrimitives(PrimitiveType.LineStrip, vertices2, 0, vertices2.Length, indices2, 0, indices2.Length - 1);
            }

            base.Draw(gameTime);
        }
    }
}
```

**Comment by jsmars** [comment]
I'm glad that there is a logical solution to the problem so that I can correct my shaders to the correct way! However, since this (bad) behavior does work fine in XNA and previous versions of FNA, and FNA is focused on XNA accuracy, shouldn't this be supported in some way anyway? Or at least be giving a more verbose expection explaining whats wrong, since I think I won't be the first person to run into when porting older projects that work fine in previous versions and XNA.

Also, while the exception problem is answered, I still can't get the wire to draw correctly with any of your fixed versions. All the vertex attributes are assigned in your example using `VertexPositionNormalColor`, which they also were in my previous example using `VertexPositionColor`, and even if I use say the built in type `VertexPositionColorTexture` that includes a texture coordinate and assign it, I still will get an invalid positions for the wireframe vertices as in the above image when using DX11. 

Isn't line strip supported when using `BasicEffect` then, or am I missing something else again? In any case this may also be a situation where accuracy should be considered and possibly a verbose warning, no?

**Comment by flibitijibibo** [comment]
You will need to implement all of that in FNA3D yourself, as this is not a scenario we found when running through our shipping tests.

**Comment by flibitijibibo** [comment]
This at least fixes line strips:

https://github.com/FNA-XNA/FNA3D/commit/2d8cfbea387eeec4fea617e1a6c24841c9f6cb9c

**Comment by jsmars** [comment]
Fair enough, and thanks for the fix!

Did I miss something on what I needed to do to get the line strips working without the fix more properly? From what I could see I had all the vertex attributes assigned. I'd be glad to do it differently and without the fix if there was a more correct and cheaper solution.

**Comment by flibitijibibo** [comment]
The VertexDeclaration must match the vertex shader's input attributes _exactly_. Given the following vertex shader...

```
void VS(
    inout float3 position : POSITION0,
    inout float4 color : COLOR0,
    inout float2 texture : TEXTURE0
);
```

... you can use something like VertexPositionColorTexture, but you can NOT use VertexPositionColor, VertexPosition, VertexPositionNormalTexture, etc. Check the VertexDeclaration if you are not sure that the vertex data matches the vertex shader. D3D9/OpenGL have it in the specification that an unmatched attribute will be a specific dummy value, but no other API does this - you have to set up placeholder vertex data manually for Metal, D3D11, Vulkan, and every console API as far as I know.

**Comment by jsmars** [comment]
Looked into this some more, and it seems there is a problem with drawing a combination of TraingleList and LineStrip using the same effect. 

I'm sure in most cases it's an easy one to one relationship between the code and effect since most things are made as custom effects and you only create what you use, but now that I look over the BasicEffect say, there are 20 different vertex shaders, that use 11 different vertex input semantic constellations depending on which settings you use. This may be obvious most of the time what you need to supply the shader, but without an exception that tells you what you are missing, or at least what it expects, I think there may be many obscure debugging cases where it's just trial and error until you get it right (and trying to figure out which semantics the BasicEffect is a bit tedious). For the SEHException you will at least throw an exception, but for the LineStrip you will just get invalid drawing without any explanation what so ever.

Please excuse my persistence on this and excuse the long post, I still don't quite understand what I'm doing wrong and I would like to get things as correct as possible without unnecessarily forcing the driver to do any extra work that could slow things down. I've split it into 4 questions to make it a bit easier to shut me ut 😆 

I've updated the example so you can test the results, with convenient toggle keys to test all combinations. Please see if you can find a way to get the wire to draw correctly using any combination of vertex declaration. Using VertexPositionColorTexture as you suggestions does not currently work. Please note: for the example I modified BasicEffect a bit to be able to output which vertexinput and semantics it is using so you need to use the FNA.dll in the file for it to work. 

1. Is it not allowed to draw a mixture of both LineStrip and TriangleList using the same effect as it is in OpenGL/Vulkan? The second drawing will have it's invalid vertex data for some reason. 

2. If we aren't allowed to using multiple types for same effect, are there any other limitations? I noticed there is mojoshader assertion if you try to clone an effect after it has been used (press 5 in the sample). Should I open another issue for this or am I doing something wrong here also?

> Assertion failure at MOJOSHADER_cloneEffect (mojoshader_effects.c:1514), triggered 1 time: 'clone->current_pass == -1'

3. With your fix it works, but I still can't get the wire to draw correctly without your it when drawing both cubes, or is that a required fix regardless? 

4. Is there any easy way to figure out which input semantics any effect is asking for and supplied with without looking at the HLSL source? I would gladly like to write a little exception of my own on any missmatch if possible. (The sample is a custom copy of semantics that only works for BasicEffect)

As you can see in these screenshots I'm supplying exactly what the shader is asking for, yet the wire will never draw correctly on DX11, except if I switch the drawing order, then the colored cube will never draw correctly. As expected an (obscure) exception is thrown if the shader is asking for more than it's recieving.

![image](https://user-images.githubusercontent.com/5105918/92889246-56be6e80-f416-11ea-9a98-6134a98c6173.png)

![image](https://user-images.githubusercontent.com/5105918/92889338-6ccc2f00-f416-11ea-8709-87dc64d717d3.png)

![image](https://user-images.githubusercontent.com/5105918/92889391-79e91e00-f416-11ea-8cb6-139c0e464cec.png)

**Comment by flibitijibibo** [comment]
You will want to learn to use RenderDoc, as it answers just about every question that's not crash-related: https://renderdoc.org/
