### ISSUE TITLE
D3D11 Uniform Buffer Bools Incorrect Spacing

### ISSUE THREAD

**Issue by jeffphilp** [FNA-XNA/FNA3D#55]
I have a shader which runs correctly under the OpenGL backend, but not under the D3D11 backend with the symptom being a boolean in the uniform buffer appeared to have the wrong value (this was verifed by setting some colours in various branches of the shader).

I have run it against a version of FNA3D.dll with debug in it, and verified:
1. That the output hlsl looks sane.
2. The boolean values are being correctly picked up and set in mojoshader_d3d11.dll | update_uniform_buffer

I then ran it against renderdoc which showed:
![RenderDoc](https://user-images.githubusercontent.com/8654118/95838467-4ba48880-0d9e-11eb-880b-36a169d1d85a.png)
that it believed not enough bytes had been provided.  (uniforms_bool[4] should be true)

So the problem appears to be that each boolean variable is expecting to be found every 16 bytes :/

So I made, hacky, changes to my local version:
1. Setting the size to 16 in MOJOSHADER_d3d11CompileShader for MOJOSHADER_UNIFORM_BOOL instead of 1.
2. In update_uniform_buffer I had it set the size for MOJOSHADER_UNIFORM_BOOL to 16, and point src at a uint32[4] array with the low int being populated with the boolean uint8 value.

This fixes the problem, as can be seen in the renderdoc screenshot.
![image](https://user-images.githubusercontent.com/8654118/95838671-8c9c9d00-0d9e-11eb-804f-023703437659.png)
uniforms_bool[4] is now true and the shader appears to be working.

I'm hoping the DirectX experts out there :) might be in a position to understand if this diagnosis is correct and the best way of resolving it.  I know it's likely a mojoshader issue, however my understanding is that the hlsl implementation originated with this project so this would be the best place to start a discussion on it.

**Comment by flibitijibibo** [comment]
Did a quick lookup and your diagnosis is correct: https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-packing-rules

Once we have your changes we'll get them integrated into MojoShader.

**Comment by jeffphilp** [comment]
This is the diff, thought it at least has the problems:
1. It allocates the 4 byte array on every call.
2. Because there is a mismatch between the internal storage format of bools (unit8) and what is expected an array_count > 1 will fail (or it needs to have some memory dynamically allocated?).

I was wondering however what does it take for the array count > 1, as it seems to treat each element of the arrays being generated by mojoshader as single elements?  Does it only kick in when an alternative packing is in use?  I have tried a fiew different varients with the /Od flag in place and it never triggers array_count != 1.

```
diff --git a/mojoshader_d3d11.c b/mojoshader_d3d11.c
index 372a4bc..70b5687 100644
--- a/mojoshader_d3d11.c
+++ b/mojoshader_d3d11.c
@@ -170,6 +170,7 @@ static void update_uniform_buffer(MOJOSHADER_d3d11Shader *shader)

     // Update the buffer contents
     int needsUpdate = 0;
+    uint32 boolValue[4] = { 0, 0, 0, 0 };
     size_t offset = 0;
     for (int i = 0; i < shader->parseData->uniform_count; i++)
     {
@@ -198,8 +199,10 @@ static void update_uniform_buffer(MOJOSHADER_d3d11Shader *shader)
                 break;

             case MOJOSHADER_UNIFORM_BOOL:
-                src = &regB[idx];
+                boolValue[0] = regB[idx];
+                src = boolValue;
                 dst = shader->constantData + offset;
+                size *= 16;
                 break;

             default:
@@ -628,8 +631,6 @@ MOJOSHADER_d3d11Shader *MOJOSHADER_d3d11CompileShader(const char *mainfn,
         {
             int arrayCount = pd->uniforms[i].array_count;
             int uniformSize = 16;
-            if (pd->uniforms[i].type == MOJOSHADER_UNIFORM_BOOL)
-                uniformSize = 1;
             retval->buflen += (arrayCount ? arrayCount : 1) * uniformSize;
         } // for
```

**Comment by flibitijibibo** [comment]
The stack allocation isn't so bad IMO... might be a way to optimize the zeroing of those elements but it's not the end of the world. I think the only issue is, as you say, with the array size. I think all that's needed there is a path to manually loop through the constant buffer and assign each element and increment the array index along with the stride, which may actually fix the uint32[4] problem at the same time anyway (at the cost of it not being _nearly_ as nice as float4/int4, but it's bool registers so what can you do).

In either case I'll CC @TheSpydog just in case, but AFAIK this is already on the right track.

**Comment by jeffphilp** [comment]
Thanks, yeah looping through with separate indexes and stride was something I thought of doing when you asked for the git diff but thought it was best just to show the smallest change required.  If I can be of any assistance with testing / coding please ask.

Just for interest, the reason there is so many booleans in there (which I appreciate is unncessary switching in the shaders) is because this comes from a general purpose shader which sits behind a 3d cad like program and it is compiled on the fly with a variety of different defines - and the booleans act to switch between different light sources, enabling specular etc. on the fly.

**Comment by TheSpydog** [comment]
Yeah, if you could follow flibit's suggestion about looping through the constant buffer, that'd be great. AFAIK this is the first test case for boolean registers that we've seen for the D3D11 backend (hence their brokenness :)) so if you write a solution that works for you and doesn't touch anything outside the bool register path, I'll sign off on it.

(And thanks for explaining why the bools are there, I was curious!)

**Comment by jeffphilp** [comment]
@TheSpydog So would something along the lines of this be too much because it does touch the float and int paths slightly in:
1. Using a compare flag to turn enable the memcmp check at the bottom for non booleans
2. Refactors the common size calculation up the top.

My c skills are not great, so there is probably a better version for the memcmp used in the boolean case statement as well.

Its probably excessive here, but you can do shader reflection to work out the locations of all the uniforms if you ever wanted a guarenteed way to ensure things were placed in the correct location - though you would want to store those results somewhere to avoid the lookup every frame.

```
diff --git a/mojoshader_d3d11.c b/mojoshader_d3d11.c
index 372a4bc..33bfec1 100644
--- a/mojoshader_d3d11.c
+++ b/mojoshader_d3d11.c
@@ -181,25 +181,37 @@ static void update_uniform_buffer(MOJOSHADER_d3d11Shader *shader)

         void *src = NULL;
         void *dst = NULL;
-        size_t size = arrayCount ? arrayCount : 1;
+        size_t numVars = arrayCount ? arrayCount : 1;
+        size_t size = numVars * 16;
+        int compare = 0;

         switch (shader->parseData->uniforms[i].type)
         {
             case MOJOSHADER_UNIFORM_FLOAT:
                 src = &regF[4 * idx];
                 dst = shader->constantData + offset;
-                size *= 16;
+                compare = 1;
                 break;

             case MOJOSHADER_UNIFORM_INT:
                 src = &regI[4 * idx];
                 dst = shader->constantData + offset;
-                size *= 16;
+                compare = 1;
                 break;

             case MOJOSHADER_UNIFORM_BOOL:
-                src = &regB[idx];
-                dst = shader->constantData + offset;
+                for (int b = 0; b < numVars; b++)
+                {
+                    src = &regB[idx + b];
+                    dst = shader->constantData + (offset + 16 * b);
+                    if (memcmp(dst, src, 1) != 0)
+                    {
+                        memcpy(dst, src, 1);
+                        needsUpdate = 1;
+                    } // if
+                } // for
+
+                compare = 0;
                 break;

             default:
@@ -207,7 +219,7 @@ static void update_uniform_buffer(MOJOSHADER_d3d11Shader *shader)
                 break;
         } // switch

-        if (memcmp(dst, src, size) != 0)
+        if (compare && memcmp(dst, src, size) != 0)
         {
             memcpy(dst, src, size);
             needsUpdate = 1;
@@ -215,7 +227,7 @@ static void update_uniform_buffer(MOJOSHADER_d3d11Shader *shader)

         offset += size;
     } // for
-
+
     if (needsUpdate)
     {
         // Map the buffer
@@ -628,8 +640,6 @@ MOJOSHADER_d3d11Shader *MOJOSHADER_d3d11CompileShader(const char *mainfn,
         {
             int arrayCount = pd->uniforms[i].array_count;
             int uniformSize = 16;
-            if (pd->uniforms[i].type == MOJOSHADER_UNIFORM_BOOL)
-                uniformSize = 1;
             retval->buflen += (arrayCount ? arrayCount : 1) * uniformSize;
         } // for
```

**Comment by flibitijibibo** [comment]
This should be enough for us to go on - I'll clean this up and get it into upstream tomorrow if nobody beats me to it.

**Comment by flibitijibibo** [comment]
Pushed to MojoShader, updated fnalibs:

https://hg.icculus.org/icculus/mojoshader/rev/f6fbe7e72735
