### ISSUE TITLE
RenderTarget2D creation issue on macOS

### ISSUE THREAD

**Issue by HybridBeasts** [FNA-XNA/FNA3D#56]
We encountered a situation where FNA is behaving differently on macOS compared to XNA/FNA on Windows or FNA on Linux. In our game Hybrid Beasts, the rendered terrain is composed of tiled textures whose color is updated from an internal datastructure `colors` and then rendered into a `RenderTarget2D` named `renderTarget` using an intermediate (re-used) texture `tempTileTexture`. The `renderTarget` of all tiles is then drawn to show the current level.

The issue can be reproduced on macOS simply by starting into the first level of the [free demo of Hybrid Beasts](https://store.steampowered.com/app/427830/Hybrid_Beasts/) .

The code for one tile looks like this:

    // Copy colors from color-array into tile texture for a specific tile`
    public void RefreshTexture()`
    {
       AresGame.Ares.GetGraphicsDevice().Textures[0] = null; // Prelim: Why is this needed

       // Write changed colors to temp texture
       tempTileTexture.SetData<Color>(colors);

       // Set renderer to tile rendertarget
       AresGame.Ares.GetGraphicsDevice().SetRenderTarget(renderTarget);

       // Clear
       AresGame.Ares.GetGraphicsDevice().Clear(Color.Transparent);

       // Create updated (mipmapped) rendertarget by drawing tempTileTexture into it
       DrawEngine.spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend);
       DrawEngine.spriteBatch.Draw(tempTileTexture, Vector2Constants.Zero, Color.White);
       DrawEngine.spriteBatch.End();
    }

Here is how the result looks on **macOS**: 
Only tiles with (even tiny) fragments of terrain in it are drawn, all others are transparent. However, here these tiles all show the same texture (_maybe_ the lower right / last created tiles). 

![20201013_135216505_iOS](https://user-images.githubusercontent.com/72838905/95927126-45260900-0dbe-11eb-82b5-38c350b08ccc.jpg)

Here is how a similar scene looks on **Windows**:
Here all tiles show the correct representation of the internal terrain data.

![20201013_231216240_iOS](https://user-images.githubusercontent.com/72838905/95927199-6850b880-0dbe-11eb-9611-e95e78df85ea.jpg)

**Comment by TheSpydog** [comment]
It looks correct on my machine. What hardware are you testing with?

**Comment by HybridBeasts** [comment]
We use two Mac Mini (2017 & 2018) for testing. Maybe the integrated Intel graphics are the problem? Are these not fully compatible with FNA?

**Comment by TheSpydog** [comment]
Integrated graphics cards are definitely supported by FNA. I'm using a MacBook Pro 2016 with an Intel Iris Graphics 540.

Something I just found -- if I launch the game directly from Steam, everything renders as it should. If I run the executable manually with mono, it displays incorrectly, just like in your screenshot. Very odd.

@flibitijibibo Any ideas?

**Comment by flibitijibibo** [comment]
Does running it outside of Steam with the kick binary have any impact?

**Comment by TheSpydog** [comment]
Running with the kick binary looks the same as when running with mono. Interestingly, macOS is complaining that the .app "file" is malformed when I try to directly open it. Might be related...?
```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3665, _LSFunction=_LSOpenStuffCallLocal}
```

**Comment by flibitijibibo** [comment]
I feel like it might be missing something important in Info.plist... the app being corrupt actually would explain weird issues since the base directory heavily depends on the app bundle's structure.

**Comment by HybridBeasts** [comment]
Well, this is the current Info.plist. I wonder how this could impact the tile rendering.

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>CFBundleDevelopmentRegion</key>
        <string>en</string>
        <key>CFBundleExecutable</key>
        <string>HybridBeasts_FNA</string>
        <key>CFBundleIconFile</key>
        <string>HybridBeasts_FNA</string>
        <key>CFBundleIdentifier</key>
       <string>com.hybridbeasts.www</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>Hybrid Beasts</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>0.133.7</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleVersion</key>
        <string>1</string>
        <key>LSApplicationCategoryType</key>
        <string>public.app-category.games</string>
        <key>LSMinimumSystemVersion</key>
        <string>10.6</string>
        <key>NSHumanReadableCopyright</key>
        <string>Copyright © 2020 BeastBits. All rights reserved.</string>
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
    </dict>
    </plist>

**Comment by HybridBeasts** [comment]
We just realized that (probably unrelated to that graphical issue) we are currently using the same plist files for the demo and the full version that start with differently named executable names (HybridBeasts_FNA = full, HybridBeasts_Demo = demo). The current plist file points to the executable name of the full version. Since these two version share all the data (and only differ in the executables), we probably would need two Info.plist files if possible (or we need to senselessly duplicate the game data on macOS).

**Comment by flibitijibibo** [comment]
The demo and full version should be different appids and depots to begin with, no?

**Comment by HybridBeasts** [comment]
The idea was to share an installation directory between demo and full version to prevent to need to re-download Hybrid Beasts when purchasing the full version after trying out the demo. The only difference really is the executable, 95% of the data (~800 MB) are the same.
On Windows and Linux it seems no problem having two executables in the same game directory.

**Comment by flibitijibibo** [comment]
Different platforms have different needs - I would strongly suggest splitting the executables out into separate depots and having the content be shared in a single depot, or using the Steamworks APIs to determine if the user owns the appid in question. Trying to sidestep the plist isn't going to happen.

**Comment by HybridBeasts** [comment]
Well, completely agreed. The plist issue for the demo will be fixed asap. However, since the plist is correct for the full version, and the graphical issue persists there, this is unlikely to be the cause of original issue?

**Comment by flibitijibibo** [comment]
An apitrace of both scenarios should be able to verify any differences between the two scenarios. I don't know how easy this is on macOS though, you may only be able to capture an instance outside of Steam (but that's what we care about anyway).

**Comment by HybridBeasts** [comment]
> 
> 
> Integrated graphics cards are definitely supported by FNA. I'm using a MacBook Pro 2016 with an Intel Iris Graphics 540.
> 
> Something I just found -- if I launch the game directly from Steam, everything renders as it should. If I run the executable manually with mono, it displays incorrectly, just like in your screenshot. Very odd.
> 
> @flibitijibibo Any ideas?

The plist issue is now fixed. Interestingly, with an additional reinit of the rendertargets and by passing /gldevice:OpenGL as a launch argument, it now works when started directly from Steam. Do you still get the error when starting the game from outside Steam but using /gldevice:OpenGL as a launch argument ?

**Comment by TheSpydog** [comment]
> Do you still get the error when starting the game from outside Steam but using /gldevice:OpenGL as a launch argument ?

The game works fine when launched outside of Steam using the OpenGL backend. I believe the Steam configuration for the game always forces OpenGL, which would explain why it has always worked for me when starting it with Steam.

I've found the bug with the FNA3D Metal backend, but it may take some time to fix. I should be able to get it working either by tonight or this weekend. But in the meantime, forcing the GL backend like you're already doing is a sufficient solution.

**Comment by HybridBeasts** [comment]
For us, using the GL backend is completely fine since we see not substancial difference in performance. Would you in general recommend using Metal on macOS?

**Comment by flibitijibibo** [comment]
Metal is nice to have, but you may want to have it as a separate launch option.

Depending on how Vulkan goes we may end up deprecating the direct Metal renderer in favor of MoltenVK, but we need to do a LOT of work on Vulkan first before we even start that assessment.

**Comment by TheSpydog** [comment]
Fixed by https://github.com/FNA-XNA/FNA3D/commit/1f7acd05da4468ad701022263aa2ffc34780c34f.
