### ISSUE TITLE
`Render Pipeline Descriptor Validation

### ISSUE THREAD

**Issue by lihaochen910** [FNA-XNA/FNA3D#62]
OS: MacOS Big Sur Beta
Device: MBP2015

FNA3D Driver: Metal
Device Name: Intel Iris Pro Graphics
validateWithDevice:2556: failed assertion `Render Pipeline Descriptor Validation
No valid pixelFormats set.
'

/Library/Frameworks/Mono.framework/Versions/6.12.0/bin/mono-sgen64 /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/FNATemplate.exe
objc[63321]: Class SDLApplication is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67ba18) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924c38). One of the two will be used. Which one is undefined.
objc[63321]: Class SDLAppDelegate is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67ba68) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924c88). One of the two will be used. Which one is undefined.
objc[63321]: Class SDLTranslatorResponder is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bae0) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924d00). One of the two will be used. Which one is undefined.
objc[63321]: Class SDLMessageBoxPresenter is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bb08) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924d28). One of the two will be used. Which one is undefined.
objc[63321]: Class SDL_cocoametalview is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bb58) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924d78). One of the two will be used. Which one is undefined.
objc[63321]: Class SDLOpenGLContext is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bba8) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924dc8). One of the two will be used. Which one is undefined.
objc[63321]: Class SDLWindow is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bbf8) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924e18). One of the two will be used. Which one is undefined.
objc[63321]: Class Cocoa_WindowListener is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bc20) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924e40). One of the two will be used. Which one is undefined.
objc[63321]: Class SDLView is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bc98) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924eb8). One of the two will be used. Which one is undefined.
objc[63321]: Class METAL_RenderData is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bce8) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924f08). One of the two will be used. Which one is undefined.
objc[63321]: Class METAL_TextureData is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bd38) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924f58). One of the two will be used. Which one is undefined.
FNA3D Driver: Metal
Device Name: Intel Iris Pro Graphics
validateWithDevice:2556: failed assertion `Render Pipeline Descriptor Validation
No valid pixelFormats set.
'

=================================================================
        Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x10afc3779 - /Library/Frameworks/Mono.framework/Versions/6.12.0/bin/mono-sgen64 : mono_dump_native_crash_info
        0x10af5b5be - /Library/Frameworks/Mono.framework/Versions/6.12.0/bin/mono-sgen64 : mono_handle_native_crash
        0x10afc2d42 - /Library/Frameworks/Mono.framework/Versions/6.12.0/bin/mono-sgen64 : sigabrt_signal_handler
        0x7fff20542d7d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
        0x1a - Unknown
        0x7fff20450720 - /usr/lib/system/libsystem_c.dylib : abort
        0x7fff2044f9d6 - /usr/lib/system/libsystem_c.dylib : err
        0x7fff28559914 - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : _Z13MTLGetEnvCaseI16MTLErrorModeTypeEbPKcRT_RKSt16initializer_listINSt3__14pairIS2_S3_EEE.cold.1
        0x7fff28547dd2 - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : MTLReportFailure
        0x7fff28541b8a - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : _MTLMessageContextEnd
        0x7fff28546ed8 - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : _ZL18validateWithDevicePU19objcproto9MTLDevice11objc_objectRK34MTLRenderPipelineDescriptorPrivate
        0x7fff28546418 - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : -[MTLRenderPipelineDescriptorInternal validateWithDevice:error:]
        0x7fff2852f005 - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : -[MTLCompiler newRenderPipelineStateWithDescriptorInternal:options:reflection:destinationBinaryArchive:error:completionHandler:]
        0x7fff284b36b3 - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : -[MTLCompiler newRenderPipelineStateWithDescriptor:options:reflection:error:completionHandler:]
        0x7fff284b2e90 - /System/Library/Frameworks/Metal.framework/Versions/A/Metal : -[_MTLDevice newRenderPipelineStateWithDescriptor:error:]
        0x10e50ef7d - /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libFNA3D.0.dylib : METAL_CreateDevice
        0x1165b5a86 - Unknown
        0x1165afac3 - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x123145481232384x from 0x4517445120x
Entering thread summarizer pause from 0x4517445120x
Finished thread summarizer pause from 0x4517445120x.
Failed to create breadcrumb file (null)/crash_hash_0x1bdcc2f03

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================

=================================================================
        Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff204cf4f2):0x7fff204cf4e2  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x7fff204cf4f2  73 08 48 89 c7 e9 35 a2 ff ff c3 90 90 90 b8 53  s.H...5........S
0x7fff204cf502  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 1d a2  ...I....s.H.....
0x7fff204cf512  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at Microsoft.Xna.Framework.Graphics.FNA3D:FNA3D_CreateDevice <0x000a5>
          at Microsoft.Xna.Framework.Graphics.GraphicsDevice:.ctor <0x00532>
          at Microsoft.Xna.Framework.GraphicsDeviceManager:Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice <0x002e2>
          at Microsoft.Xna.Framework.Game:DoInitialize <0x00144>
          at Microsoft.Xna.Framework.Game:Run <0x0006a>
          at Unnamed.Engine.UnnamedEngine:Run <0x0005a>
          at Unnamed.Engine.UnnamedEngine:Begin <0x000f2>
          at FNATemplate.Program:Main <0x0035a>
          at <Module>:runtime_invoke_void_object <0x000b0>
=================================================================

Process finished with exit code 6.

**Comment by flibitijibibo** [comment]
The bug is that you are using a system runtime:

```
Class SDLMessageBoxPresenter is implemented in both /usr/local/Cellar/sdl2/2.0.12/lib/libSDL2-2.0.0.dylib (0x10e67bb08) and /Users/Kanbaru/OneDrive/Documents/FSOnCSharp/Unnamed.Engine.Template/bin/Debug/libSDL2-2.0.0.dylib (0x112924d28). One of the two will be used. Which one is undefined.
```

You will need to fix your DYLD_LIBRARY_PATH, or use MonoKickstart instead:

https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#i-have-a-bug-when-running-on-system-mono-and-
