### ISSUE TITLE
FNA 21.01 crashes on DrawUserPrimitives

### ISSUE THREAD

**Issue by danielcrenna** [FNA-XNA/FNA3D#92]
When running FNA 21.01 (notable difference being the introduction to FNA3D), calls to DrawUserPrimitives crashes via FNA3D with:

`System.InvalidOperationException: 'Could not compile input layout! Error Code: The parameter is incorrect. (0x80070057)'`

Attached are two simple repros, one is running 20.05, which renders correctly, and one is running 21.01, which seems to crash with the above mentioned error.

The error occurs when `VertexPositionTexture` is used with a Texture2D. It works when `VertexPositionColor` is used (`DrawCube`, in the example, vs. `DrawTexturedCube`)

[humans-20.05.zip](https://github.com/FNA-XNA/FNA3D/files/5859756/humans-20.05.zip)
[humans-21.01.zip](https://github.com/FNA-XNA/FNA3D/files/5859757/humans-21.01.zip)

**Comment by flibitijibibo** [comment]
The shaders will be what matters in this case - here's where the issue occurs: https://github.com/FNA-XNA/FNA3D/blob/master/src/FNA3D_Driver_D3D11.c#L971

Usually this trips when the input layout does not match the vertex shader input parameters. This can be compared by running with /gldevice:OpenGL as a launch option.

**Comment by flibitijibibo** [comment]
I was able to verify that DrawTexturedCube is violating the modern API requirement of vertex input layout matching - if you comment `effect.EnableDefaultLighting()` or use `VertexPositionNormalTexture` for vertices instead, rendering works correctly.

Forcing OpenGL works around this, but note that this is _very_ much API-dependent - OpenGL/D3D9 had a very quiet feature that set unused vertex attribs to 0, but this is surprisingly wasteful in terms of resource usage and performance! No other API allows this anymore, including D3D10+, Vulkan, and console graphics APIs. It'd be possible to emulate the 0 attribute if someone _really_ wanted to write it, but in writing it you would see just how wasteful it can be.

OpenGL provides the best XNA4 accuracy here and I wouldn't judge anyone for forcing OpenGL to preserve XNA4 behavior, but definitely be sure to match up input/output shader semantics both for vertex input _and_ pixel input if you want the best performance and portability!

**Comment by danielcrenna** [comment]
@flibitijibibo That makes perfect sense, thanks for the detailed answer and taking the time to educate me on it. That's sneaky alignment happening in OpenGL.
